config/routes.rb
Rails.application.routes.draw do
  root 'auth#index'

  get '/auth/github', to: 'auth#login'
  get '/auth/github/callback', to: 'auth#callback'
  delete 'logout', to: 'auth#logout', as: :logout
  get '/user_profile', to: 'auth#user_profile', as: :user_profile
  resources :repositories do
    get "more", on: :collection
    put "star", on: :member
    put "unstar", on: :member
    get "/:owner/:name/stargazers", on: :member, to: 'repositories#stargazers', as: :stargazers
    get "/:owner/:name/more_stargazers", on: :member, to: 'repositories#more_stargazers', as: :more_stargazers
    get "/:owner/:name/issues", on: :member, to: 'repositories#issues', as: :issues
    get "/:owner/:name/more_issues", on: :member, to: 'repositories#more_issues', as: :more_issues
  end

  get '/repositories', to: 'repositories#index', as: :repository_list

end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  include RepoAuthen
  # Define query for repository listing.
  
  IndexQuery = RepoAuthen::Client.parse <<-'GRAPHQL'
    # All read requests are defined in a "query" operation
    query {
      # viewer is the currently authenticated User
      viewer {
        ...Views::Repositories::Index::Viewer
      }
    }
  GRAPHQL

  # GET /repositories
  def index
    # Use query helper defined in ApplicationController to execute the query.
    # `query` returns a GraphQL::Client::QueryResult instance with accessors
    # that map to the query structure.

    data = query IndexQuery

    # Render the app/views/repositories/index.html.erb template with our
    # current User.
    render "repositories/index", locals: {
      viewer: data.viewer
    }
  end

  # Define query for "Show more repositories..." AJAX action.
  MoreQuery = RepoAuthen::Client.parse <<-'GRAPHQL'
    # This query uses variables to accept an "after" param to load the next
    # 30 repositories.
    query($after: String!) {
      viewer {
        repositories(first: 30, after: $after) {
          # Instead of refetching all of the index page's data, we only need
          # the data for the repositories container partial.
          ...Views::Repositories::Repositories::RepositoryConnection
        }
      }
    }
  GRAPHQL

  # GET /repositories/more?after=CURSOR
  def more
    # Execute the MoreQuery passing along data from params to the query.
    data = query MoreQuery, after: params[:after]

    render partial: "repositories/repositories", locals: {
      repositories: data.viewer.repositories
    }
  end

  # Define query for repository show page.
  ShowQuery = RepoAuthen::Client.parse <<-'GRAPHQL'
    # Query is parameterized by a $id variable.
    query($id: ID!) {
      node(id: $id) {
        # Include fragment for app/views/repositories/show.html.erb
        ...Views::Repositories::Show::Repository
      }
    }
  GRAPHQL

  # GET /repositories/ID
  def show
    data = query ShowQuery, id: params[:id]

    if repository = data.node
      render "repositories/show", locals: {
        repository: repository
      }
    else
      # If node can't be found, 404. This may happen if the repository doesn't
      # exist, we don't have permission or we used a global ID that was the
      # wrong type.repository
      head :not_found
    end
  end

  StarMutation = RepoAuthen::Client.parse <<-'GRAPHQL'
    mutation($id: ID!) {
      star(input: { starrableId: $id }) {
        starrable {
          ...Views::Repositories::Star::Repository
        }
      }
    }
  GRAPHQL

  def star
    data = query StarMutation, id: params[:id]

    if repository = data.star
      respond_to do |format|
        format.js {
          render partial: "repositories/star", locals: { repository: data.star.starrable }
        }

        format.html {
          redirect_to "/repositories"
        }
      end
    else
      head :not_found
    end
  end

  UnstarMutation = RepoAuthen::Client.parse <<-'GRAPHQL'
    mutation($id: ID!) {
      unstar(input: { starrableId: $id }) {
        starrable {
          ...Views::Repositories::Star::Repository
        }
      }
    }
  GRAPHQL

  def unstar
    data = query UnstarMutation, id: params[:id]

    if repository = data.unstar
      respond_to do |format|
        format.js {
          render partial: "repositories/star", locals: { repository: data.unstar.starrable }
        }

        format.html {
          redirect_to "/repositories"
        }
      end
    else
      head :not_found
    end
  end

  ListStargazers = RepoAuthen::Client.parse <<-'GRAPHQL'
  query($id: ID!) {
      node(id: $id) {
        ...Views::Repositories::Stargazers::Repository
      }
    }
GRAPHQL

  def stargazers
    data = query ListStargazers, id: params[:id]
    if repository = data.node
      render "repositories/stargazers", locals: {
        repository: repository
      }
    else
      head :not_found
    end
  end

  MoreStargazers = RepoAuthen::Client.parse <<-'GRAPHQL'
  query($after: String!, $owner: String!, $name: String!) {
    repository(owner:$owner, name: $name) {
      stargazers(first: 30, after: $after) {
        ...Views::Repositories::ListStargazers::StargazerConnection
      }
    }
  }
GRAPHQL

def more_stargazers
  data = query MoreStargazers, after: params[:after], owner: params[:owner], name:params[:name]

  render partial: "repositories/list_stargazers", locals: {
    stargazers: data.repository.stargazers
  }
end
  
ListIssues = RepoAuthen::Client.parse <<-'GRAPHQL'
  query($id: ID!) {
      node(id: $id) {
        ...Views::Repositories::Issues::Repository
      }
    }
GRAPHQL

  def issues
    data = query ListIssues, id: params[:id]
    if repository = data.node
      render "repositories/issues", locals: {
        repository: repository
      }
    else
      head :not_found
    end
  end

  MoreIssues = RepoAuthen::Client.parse <<-'GRAPHQL'
  query($after: String!, $owner: String!, $name: String!) {
    repository(owner:$owner, name: $name) {
      issues(first: 30, after: $after) {
        ...Views::Repositories::ListIssues::IssueConnection
      }
    }
  }
GRAPHQL

  def more_issues
    data = query MoreIssues, after: params[:after], owner: params[:owner], name:params[:name]

    render partial: "repositories/list_issues", locals: {
      issues: data.repository.issues
    }
  end

end

app/views/repositories/_icon.html.erb
<%graphql
  fragment Repository on Repository {
    isFork
    isMirror
    isPrivate
  }
%>
<% repository = Views::Repositories::Icon::Repository.new(repository) %>

<% if repository.is_fork? %>
  <span class="octicon octicon-repo-forked"></span>
<% elsif repository.is_private? %>
  <span class="octicon octicon-lock"></span>
<% elsif repository.is_mirror? %>
  <span class="octicon octicon-mirror"></span>
<% else %>
  <span class="octicon octicon-repo"></span>
<% end %>

app/views/repositories/_list_issues.html.erb
<%graphql
  fragment IssueConnection on IssueConnection {
     edges{
        node{
          title
          state
          url
          createdAt,
          body
        }
        cursor
      }
          
    # Pagination related metadata
    pageInfo {
      hasNextPage
    }
  }
%>
<% issues = Views::Repositories::ListIssues::IssueConnection.new(issues) %>

<% issue_list = issues.edges %>
  <ul class="list-group">
    <% issue_list.each_with_index do |issue, index|%>
      <li class="list-group-item">
        <span class="octicon octicon-issue-opened"></span>
        <a href="#">
          Title: <%= issue.node.title %> / Created At: <%=issue.node.createdAt.to_date.strftime("%Y-%m-%d") %>
        </a>
      </li>
    <% end %>

    <% if issues.page_info.has_next_page? %>
      <li class="list-group-item show-more text-center">
        <a class="js-load-more btn btn-primary" id="spin_wrapper" href="<%= more_issues_repository_path(after: issues.edges.last.cursor) %>">
          Load more...
        </a>
        <span class="octicon octicon-sync spinner"></span>
      </li>
    <% end %>
  </ul>

app/views/repositories/_list_item.html.erb
<%graphql
  fragment Repository on Repository {
    id
    owner {
      login
    }
    name
    stargazers {
      totalCount
    }
    ...Views::Repositories::Icon::Repository
    ...Views::Repositories::Star::Repository
  }
%>
<% repository = Views::Repositories::ListItem::Repository.new(repository) %>

<li class="list-group-item">
  <%= render "repositories/star", repository: repository %>
  <%= render "repositories/icon", repository: repository %>

  <a href="<%= repository_path(repository.id) %>">
    <%= repository.owner.login %>/<%= repository.name %>
  </a>
</li>

app/views/repositories/_list_stargazers.html.erb
<%graphql
  fragment StargazerConnection on StargazerConnection {
     edges {
        starredAt
        node {
          login
          avatarUrl
        }
        cursor
      }

    # Pagination related metadata
    pageInfo {
      hasNextPage
    }
  }
%>
<% stargazers = Views::Repositories::ListStargazers::StargazerConnection.new(stargazers) %>

<% stargazer_list = stargazers.edges %>
  <ul class="list-group">
    <% stargazer_list.each_with_index do |s, index|%>
      <li class="list-group-item">
        <span class="star-badge">
          <button>
            <span class="octicon octicon-star highlight"></span>
          </button>
        </span>
        <a href="/">
        <img src="<%= s.node.avatarUrl %>" alt="N/A" class="img-circle my-page-img">
          Stargazer Name: <%= s.node.login %> / Starred At: <%=s.starredAt.to_date.strftime("%Y-%m-%d") %>
        </a>
      </li>
    <% end %>

    <% if stargazers.page_info.has_next_page? %>
      <li class="list-group-item show-more text-center">
        <a class="js-load-more btn btn-primary" id="spin_wrapper" href="<%= more_stargazers_repository_path(after: stargazers.edges.last.cursor) %>">
          Load more...
        </a>
        <span class="octicon octicon-sync spinner"></span>
      </li>
    <% end %>
  </ul>

  

  

app/views/repositories/_navigation.html.erb
<%graphql
  fragment Repository on Repository {
    hasIssuesEnabled
    issues {
      totalCount
    }
    pullRequests {
      totalCount
    }
  }
%>
<% repository = Views::Repositories::Navigation::Repository.new(repository) %>

<ul class="nav nav-pills pull-right">
  <li role="presentation" class="active">
    <a href="#">
      <span class="octicon octicon-code"></span>
      Code
    </a>
  </li>
  <%# NOTE: has_issues_enabled is snake case here. We can also include an optional `?` %>
  <% if repository.has_issues_enabled? %>
    <li role="presentation">
      <a href="#">
        <span class="octicon octicon-issue-opened"></span>
        Issues
        <span class="badge"><%= repository.issues.total_count %></span>
      </a>
    </li>
  <% end %>
  <li role="presentation">
    <a href="#">
      <span class="octicon octicon-git-pull-request"></span>
      Pull requests
      <span class="badge"><%= repository.pull_requests.total_count %></span>
    </a>
  </li>
  <li role="presentation">
    <a href="#">
      <span class="octicon octicon-pulse"></span>
      Pulse
    </a>
  </li>
  <li role="presentation">
    <a href="#">
      <span class="octicon octicon-graph"></span>
      Graphs
    </a>
  </li>
</ul>

app/views/repositories/_repositories.html.erb
<%= javascripts 'newji'%>
<%graphql
  fragment RepositoryConnection on RepositoryConnection {
    
    edges {
      node {
        ...Views::Repositories::ListItem::Repository
      }
      cursor
    }

    # Pagination related metadata
    pageInfo {
      hasNextPage
    }
  }
%>
<% repositories = Views::Repositories::Repositories::RepositoryConnection.new(repositories) %>

<% repositories.each_node do |repository| %>
  <%= render "repositories/list_item", repository: repository %>
<% end %>

<% if repositories.page_info.has_next_page? %>
  <li class="list-group-item show-more text-center">
    <a class="js-load-more btn btn-primary" id="spin_wrapper" href="<%= more_repositories_path(after: repositories.edges.last.cursor) %>">
      Load more...
    </a>
    <span class="octicon octicon-sync spinner"></span>
  </li>
<% end %>
 

app/views/repositories/_star.html.erb
<%graphql
  fragment Repository on Repository {
    id
    viewerHasStarred
    stargazers {
      totalCount
    }
  }
%>
<% repository = Views::Repositories::Star::Repository.new(repository) %>

<span class="star-badge">
  <%= repository.stargazers.total_count %>
  <%= form_tag repository.viewer_has_starred? ? unstar_repository_path(repository.id) : star_repository_path(repository.id), method: :put, class: "star-form" do %>
    <button>
      <span class="octicon octicon-star <% if repository.viewer_has_starred? %>highlight<% end %>"></span>
    </button>
  <% end %>
</span>

app/views/repositories/index.html.erb
<% content_for :title,'GITHUB | レポジトリ' %>
<% breadcrumb_add "レポジトリリスト" %>
<%= stylesheets 'newji'%>
<%= javascripts 'newji' %>

<%graphql

  fragment Viewer on User {

    repositories(first: 30) {

      totalCount

      ...Views::Repositories::Repositories::RepositoryConnection
    }
  }
%>
<% content_for :content_header do %>

<% viewer = Views::Repositories::Index::Viewer.new(viewer) %>

<div class="repositories">
  <ul class="list-group">
    <li class="list-group-item">
      <strong>Your repositories</strong>
      <%# NOTE: total_count is snake case here %>
      <span class="badge"><%= viewer.repositories.total_count%></span>
    </li>

    <%= render "repositories/repositories", repositories: viewer.repositories %>
  </ul>
</div>

<% end %>

app/views/repositories/issues.html.erb
<% content_for :title,'GITHUB | イシュー' %>
<% breadcrumb_add "レポジトリ" %>
<% breadcrumb_add "イシューリスト" %>
<%= stylesheets 'newji'%>

<%graphql
  fragment Repository on Repository {
    id
    description
    url
    issues(states:[OPEN,CLOSED], first:30){
      totalCount,
          ...Views::Repositories::ListIssues::IssueConnection
    }
  }
%>
<% content_for :content_header do %>

<% repository = Views::Repositories::Issues::Repository.new(repository) %>

  <div class="repositories">
    <ul class="list-group">
      <li class="list-group-item">
        <strong>Repository issues quantity:</strong>
        <%# NOTE: total_count is snake case here %>
        <span class="badge"><%= repository.issues.totalCount %></span>
      </li>
      <%= render "repositories/list_issues", { issues: repository.issues} %>
    </ul>
  </div>

<% end %>

app/views/repositories/show.html.erb
<% content_for :title,'GITHUB | レポジトリ' %>
<% breadcrumb_add "レポジトリ" %>
<% breadcrumb_add "レポジトリデテール" %>

<%graphql
  fragment Repository on Repository {

    id

    owner {
      login
    }

    name

    description
    homepageUrl

    ...Views::Repositories::Navigation::Repository

    ...Views::Repositories::Star::Repository
  }
%>

<% repository = Views::Repositories::Show::Repository.new(repository) %>

<div class="header clearfix">
  <%= render "repositories/navigation", repository: repository %>

  <h3 class="text-muted inline-block">
    <a href="<%= repositories_path %>"><%= repository.owner.login %></a>
    /
    <a href="<%= repository_path(repository.id) %>"><%= repository.name %></a>
  </h3>

  <div class="inline-block star-badge-header">
    <%= render "repositories/star", repository: repository %>
  </div>
  <div class="inline-block">
    <a href="<%= stargazers_repository_path(repository.id, repository.owner.login.to_s, repository.name.to_s) %>" class="btn btn-primary">Load Stargazers</a>
  </div>

  <div class="inline-block">
    <a href="#" type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-default">Load Issues</a>
  </div>
</div>

<hr>

<div class="jumbotron">
  <h1><%= repository.name %></h1>

  <% if repository.description.present? %>
    <p><%= repository.description %></p>
  <% end %>

  <p>
    <%# NOTE: homepage_url is snake case here %>
    <% if repository.homepage_url.present? %>
      <a class="btn btn-primary btn-lg" href="<%= repository.homepage_url %>" role="button">Homepage</a>
    <% end %>

    <a class="btn btn-primary btn-lg" href="https://github.com/<%= repository.owner.login %>/<%= repository.name %>" role="button">ギットハブでレポジトリを見る</a>
  </p>
</div>

<!-- モーダル -->
<div class="modal fade" id="modal-default">
  <div class="modal-dialog modal-default">
    <div class="modal-content">
      <div class="modal-header modal-header--ordering">
        <h6 class="modal-title"><%= repository.name %>のイシューリスト</h6>
      </div>
      <div class="modal-body text-center">
        <h5 class="text-center pt-3">イシューリストショーよろしでしょうか？</h5>
        <div class="inline-block">
          <a href="<%= issues_repository_path(repository.id, repository.owner.login.to_s, repository.name.to_s) %>" class="btn btn-primary">Load Issues</a>
        </div>
        <div class="inline-block">
          <button type="button" class="btn btn-danger" data-dismiss="modal">閉じる</button>
        </div>
        
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
 </div> 

app/views/repositories/stargazers.html.erb
<% content_for :title,'GITHUB | スターゲイザー' %>
<% breadcrumb_add "レポジトリ" %>
<% breadcrumb_add "スターゲイザーリスト" %>
<%= stylesheets 'newji'%>

<%graphql
  fragment Repository on Repository {
    id
    viewerHasStarred
    stargazers(first: 30){
      totalCount,
        ...Views::Repositories::ListStargazers::StargazerConnection
    }
  }
%>

<% content_for :content_header do %>

<% repository = Views::Repositories::Stargazers::Repository.new(repository) %>

  <div class="repositories">
    <ul class="list-group">
      <li class="list-group-item">
        <strong>Repository stargazers quantity:</strong>
        <%# NOTE: total_count is snake case here %>
        <span class="badge"><%= repository.stargazers.totalCount %></span>
      </li>
      <%= render "repositories/list_stargazers", { stargazers: repository.stargazers} %>
    </ul>
  </div>

<% end%>