config/routes.rb
Rails.application.routes.draw do
  root 'auth#index'

  get '/auth/github', to: 'auth#login'
  get '/auth/github/callback', to: 'auth#callback'
  delete 'logout', to: 'auth#logout', as: :logout
  get '/user_profile', to: 'auth#user_profile', as: :user_profile
  resources :repositories do
    get "more", on: :collection
    put "star", on: :member
    put "unstar", on: :member
    get "/:owner/:name/stargazers", on: :member, to: 'repositories#stargazers', as: :stargazers
    get "/:owner/:name/more_stargazers", on: :member, to: 'repositories#more_stargazers', as: :more_stargazers
    get "/:owner/:name/issues", on: :member, to: 'repositories#issues', as: :issues
    get "/:owner/:name/more_issues", on: :member, to: 'repositories#more_issues', as: :more_issues
  end

  get '/repositories', to: 'repositories#index', as: :repository_list

end

app/views/layouts/_breadcrumb.html.erb
<ol class="breadcrumb float-sm-right">
  <% ol.each_with_index do |n, index| %>
    <% if index == ol.count-1 %>
      <li class="breadcrumb-item active"><%= n[:title] %></li>
      <% next %>
    <% end %>

    <li class="breadcrumb-item"><%= link_to n[:title], n[:url] %></li>
  <% end %>
</ol>

app/views/layouts/_navbar.html.erb
<%= javascripts 'newji'%>

<nav class="main-header navbar navbar-expand navbar-blak header-blue-primary">
  <a class="nav-link js-click-a" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Notifications Dropdown Menu -->
    <li class="nav-item">
      <a class="nav-link" data-toggle="dropdown" href="#" title="アバーテ">
        <%= image_tag "#{User.first.avartar}", class: 'img-circle my-page-img user_img', alt: 'User Image', height: '35', width: '35' %>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="dropdown" href="#" title="ユーザーネーム">
        <span><%=User.first.present? ? User.first.username : 'Unnamed'%></span>
      </a>
    </li>
     <li class="nav-item">
      <%= link_to "ログアウト", logout_path, method: "delete", class: "btn btn-primary logout", title: "ログアウト" %>
    </li>
  </ul>
  
</nav>

app/views/layouts/_sidebar.html.erb
<aside class="main-sidebar sidebar-blue-primary elevation-4">
  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class with font-awesome or any other icon font library -->
        <li class="nav-item">
          <a href ="<%= user_profile_path %>" class="nav-link w-100">
            <i class="nav-icon fas fa-sign-out-alt"></i>
            <p>
              ユーザーロフィール
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href ="<%= repository_list_path %>" class = "nav-link w-100">
            <i class="nav-icon fas fa-sign-out-alt"></i>
            <p>
              レポジトリ　リスト
            </p>
          </a>  
        </li>
        <li class="nav-item">
          <a href ="https://github.com/<%= current_user.username %>" class="nav-link w-100">
            <i class="nav-icon fas fa-sign-out-alt"></i>
            <p>
              ギットハブで見る
            </p>
          </a>
        </li>
        <!-- Logout do not have in design -->
        <li class="nav-item">
          <a href ="<%= logout_path %>" data-method="delete" class = "nav-link w-100">
          <i class="nav-icon fas fa-sign-out-alt"></i>
          <p>
            ログアウト
          </p>
          </a>
        </li>
      </ul>
    </nav>
  </div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="/octicons.min.css">
    <link rel="stylesheet" href="/application.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag 'plugins/fontawesome-free/css/all.min'%>

    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    
    <!-- Bootstrap 4.0 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Theme style -->
    <%= stylesheet_link_tag 'css/adminlte.min'%>
    <!--独自のスタイル-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :head %>
  </head>
  
  <% if current_user.present? %>
    <body class="hold-transition">
      <div class="wrapper">
      <!-- Navbar -->
        <%= render "layouts/navbar" %>
        <!-- Main Sidebar Container -->
        <%= render "layouts/sidebar" %>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
          <!-- Content Header (Page header) -->
          <div class="content-header">
            <div class="container-fluid">
              <div class="row mb-2">
                <div class="col-sm-6">
                </div>
                <div class="col-sm-6">
                  <%= render_breadcrumb %>
                </div>
              </div>
              <%= yield :content_header %>
            </div>
          </div>
          <!-- Main content -->
          <div class="content">
            <%= yield %>
          </div>
        </div>
      </div>
    </body>
  <% else %>
    <body class="hold-transition login-page">
      <%= yield %>
    </body>
  <% end %>
  
</html>